### ISSUE TITLE
Example build failed

### ISSUE THREAD

**Issue by andrescaroc** [open-telemetry/opentelemetry-rust#751] opened 2022-03-10 05:15 UTC
Hello, I just clone this repo and I was trying to run one of the examples (basic-otlp) but I get this error:
```bash
$ cargo run
...
   Compiling tracing-futures v0.2.5
   Compiling opentelemetry-api v0.1.0 (/home/andres/github/opentelemetry-rust/opentelemetry-api)
   Compiling prost-types v0.9.0
   Compiling hyper v0.14.17
   Compiling opentelemetry-sdk v0.1.0 (/home/andres/github/opentelemetry-rust/opentelemetry-sdk)
   Compiling tonic-build v0.6.2
   Compiling opentelemetry-proto v0.1.0 (/home/andres/github/opentelemetry-rust/opentelemetry-proto)
error: failed to run custom build command for `opentelemetry-proto v0.1.0 (/home/andres/github/opentelemetry-rust/opentelemetry-proto)`

Caused by:
  process didn't exit successfully: `/home/andres/github/opentelemetry-rust/target/debug/build/opentelemetry-proto-a4c345df12f52931/build-script-build` (exit status: 1)
  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: src/proto/opentelemetry-proto/opentelemetry/proto/common/v1/common.proto: No such file or directory\n" }
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I have tried with other examples, but always get a similar error. 

Is there a special command to build and run them, that maybe is missing in the README?

```bash
$ cargo --version
cargo 1.59.0 (49d8809dc 2022-02-10)
```

**Comment by TommyCpp** [comment] 2022-03-10 06:03
It looks like you are missing the proto files, which is a submodule in this repo. Could you check if there is anything in `PROJECT_ROOT/opentelemetry-proro/proto/opentelemetry-proto`?

If there is nothing. You may need to update 
```
git submodule init
git submodule update
```
to get the content of the submodule.

**Comment by TommyCpp** [comment] 2022-03-16 05:40
I will close this issue for now as I think the issue is caused by submodule is not updated. Please feel free to reopen if the problem persists after submodule updates.

**Closed by TommyCpp** 2022-03-16 05:40 UTC
Labels: question, area:common

**Comment by andrescaroc** [comment] 2022-03-16 18:12
> I will close this issue for now as I think the issue is caused by submodule is not updated. Please feel free to reopen if the problem persists after submodule updates.


Sorry for my late response. I can confirm that `git submodule init` and `git submodule update` solved my issue
