### ISSUE TITLE
[metric] How to implement a batch counter

### ISSUE THREAD

**Issue by nappa85** [open-telemetry/opentelemetry-rust#677] opened 2021-12-10 15:48 UTC
I'm trying to build a metric that sends the number of hits per page on a webserver.
Using simply `Metric::u64_counter` creates a global counter that doesn't resets at every metrics batch, this way I have an growing value tending to infinity.

Looking at `Meter` APIs, the only way I can think of is to use `Meter::batch_observer` and, inside here, use a `BatchObserver::u64_value_observer`, but to do so I have to implement myself a global counter.
Like, if I want to keep a simple global counter, an AtomicUsize would be enough, but if I want to distinct between pages, e.g. putting the path as an attribute on the observer, the situation becomes quickly complicated, like having a global HashMap with method and path as key and the counter as value and, at every batch, empty it and send all values...

Am I correct or there is a simplier way?

**Comment by nappa85** [comment] 2021-12-10 17:07
I thought about that only now, probably the best solution is to use `Metric::u64_value_recorder` and put always 1 as value, letting the consumer to sum the values in the time range, groping by attributes

**Comment by nappa85** [comment] 2021-12-13 14:45
I was wrong, the sum is still monotonically growing...
I need exact values to get what I want, so I'm back to a global hashmap to be rest at every batch...
It's a bit overcomplicated for something so simple, there isn't a better solution?

**Comment by TommyCpp** [comment] 2021-12-15 15:44
I am not sure which metrics backend you are using or if you are using collector to aggregate the raw metrics. 

But from the metrics SDK side, `counter` by design is monotonically increasing. Usually, ppl send counter to the backend and use something like the [`increase`](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) function to get the value over the last period of time

**Comment by nappa85** [comment] 2021-12-15 15:58
I'm sending metrics via otlp to an external service (newrelic).
At the moment I solved with a global hashmap and a value observer inside a batch observer.
Using a sum_value, if on first batch I had 10 hits, and on the second 6 hits, for second batch I would see 16 hits, that's not what I want

**Comment by TommyCpp** [comment] 2021-12-16 15:56
> Using a sum_value, if on first batch I had 10 hits, and on the second 6 hits, for second batch I would see 16 hits, that's not what I want

Feels like something to do with aggregation, could you share your config for the otlp exporter/pipeline? With proper setup, it should allow you to have a stateless value recorder. If it's not then we may need to investigate this as a possible bug.

**Comment by nappa85** [comment] 2021-12-16 16:11
I init metrics with a methos like that:
```rust

fn init_meter(apikey: &str) -> metrics::Result<PushController> {
    let mut map = tonic::metadata::MetadataMap::with_capacity(1);
    map.insert(
        "api-key",
        apikey.parse().unwrap(),
    );
    opentelemetry_otlp::new_pipeline()
        .metrics(spawn, delayed_interval)
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .tonic()
                .with_endpoint("https://otlp.nr-data.net:4317/")
                .with_protocol(opentelemetry_otlp::Protocol::Grpc)
                .with_metadata(map),
        )
        .with_aggregator_selector(selectors::simple::Selector::Exact)
        .with_period(Duration::from_secs(10))
        .with_resource(vec![
            KeyValue::new("service.name", "otlp-test"),
            KeyValue::new("service.namespace", "otlp-test"),
            KeyValue::new("service.instance.id", "test"),
            KeyValue::new("service.version", "0.1.0"),
        ])
        .build()
}
```

Just a side note, as you can notice I need to use tonic structs to add metadata to the call, it would be cool of opentelemetry-otlp reexporst tonic, since it isn't the latest version.

**Comment by nappa85** [comment] 2021-12-17 13:28
To give you a visual example, this is a u64_counter metric, I'm calling the single endpoints 20 times a minute, so I expect it to be a flatline, not to grow
![image](https://user-images.githubusercontent.com/7566389/146551576-fe798d1d-c78b-4c28-ab77-7f80618ff4d3.png)

**Comment by TommyCpp** [comment] 2021-12-17 14:49
Thanks for the detailed example. It's really helpful. I will try to reproduce this today. I will probably use stdout to observe the result of each batch and see if there is something wrong

**Comment by nappa85** [comment] 2021-12-17 14:57
I've made another test to clarify which element is failing, and it seems to be opentelemetry-rust.
I've attached a prometheus instance to the same collector that sends data to newrelic, the data stoppend for prometheus too:
![Screenshot_20211217_155235](https://user-images.githubusercontent.com/7566389/146563092-b975395e-4c8d-4870-a5a4-4522339c9ede.png)
![Screenshot_20211217_155256](https://user-images.githubusercontent.com/7566389/146563105-d627a451-7f8f-4aa2-9066-86e6aface37a.png)

I have no logs on my services that makes me think about some failure on otlp exporter, it always lasts more or less 10 minutes and then it stops.

**Comment by TommyCpp** [comment] 2021-12-17 15:57
Thanks. So in general we have the following issues:

- Batch seems to be accumulative instead of resetting at each reporting period
- Metrics stops to changes after a while even if it should.

**Comment by nappa85** [comment] 2021-12-17 20:03
I've been able to replicate the problem with a "minimal" example:
```rust
use futures_util::{Stream, StreamExt, Future};
use hyper::{
    body,
    service::{make_service_fn, service_fn},
    Body, Request, Response, Server,
};
use once_cell::sync::Lazy;
use opentelemetry::{
    global,
    metrics::{self, Meter, ValueRecorder, Counter},
    sdk::{metrics::{selectors, PushController}},
    KeyValue,
};
use opentelemetry_otlp::WithExportConfig;
use tokio::task::JoinHandle;
use std::time::{Duration, SystemTime};

static PUSH_CONTROLLER: Lazy<PushController> = Lazy::new(|| init_meter().unwrap());
static METER: Lazy<Meter> = Lazy::new(|| {
    Lazy::force(&PUSH_CONTROLLER);
    global::meter("abracadabra")
});
static HTTP_COUNTER: Lazy<Counter<u64>> = Lazy::new(|| {
    METER.u64_counter("hits.counter")
        .with_description("hit counter")
        .init()
});
static HTTP_REQ_HISTOGRAM: Lazy<ValueRecorder<f64>> = Lazy::new(|| {
    METER.f64_value_recorder("value.duration")
        .with_description("request latencies")
        .init()
});

// Skip first immediate tick from tokio, not needed for async_std.
fn delayed_interval(duration: Duration) -> impl Stream<Item = tokio::time::Instant> {
    println!("call to delayed_interval with duration {:?}", duration);
    opentelemetry::util::tokio_interval_stream(duration).skip(1).map(|i| {
        println!("Interval passed");
        i
    })
}

fn spawn<T>(f: T) -> JoinHandle<T::Output>
where
    T: Future + Send + 'static,
    T::Output: Send + 'static,
{
    println!("Called spawn");
    tokio::spawn(f)
}

fn init_meter() -> metrics::Result<PushController> {
    opentelemetry_otlp::new_pipeline()
        .metrics(spawn, delayed_interval)
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .tonic()
                .with_endpoint("https://127.0.0.1:4317/")
                .with_protocol(opentelemetry_otlp::Protocol::Grpc),
        )
        .with_aggregator_selector(selectors::simple::Selector::Exact)
        .with_period(Duration::from_secs(10))
        .with_resource(vec![
            KeyValue::new("service.name", "otlp-test"),
            KeyValue::new("service.namespace", "otlp-test"),
            KeyValue::new("service.instance.id", "test"),
            KeyValue::new("service.version", "0.1.0"),
        ])
        .build()
}

fn start_tracing() {
    tracing_subscriber::fmt::init();
}

fn start_metrics() {
    Lazy::force(&METER);
}

async fn serve_req(req: Request<Body>) -> Result<Response<Body>, hyper::Error> {
    let request_start = SystemTime::now();

    let attributes = &[
        KeyValue::new("method", req.method().to_string()),
        KeyValue::new("path", req.uri().path().to_owned()),
    ];

    let response = match body::to_bytes(req.into_body()).await {
        Ok(bytes) => {
            Response::builder()
                .status(200)
                .body(Body::from(bytes))
                .unwrap()
        }
        Err(e) => Response::builder()
            .status(500)
            .body(Body::from(e.to_string()))
            .unwrap(),
    };

    let duration = request_start.elapsed().unwrap_or_default();
    HTTP_REQ_HISTOGRAM.record(duration.as_secs_f64(), attributes);
    HTTP_COUNTER.add(1, attributes);

    Ok(response)
}

#[tokio::main]
async fn main() {
    start_tracing();
    start_metrics();

    let addr = ([127, 0, 0, 1], 9898).into();
    println!("Listening on http://{}", addr);

    let serve_future = Server::bind(&addr).serve(make_service_fn(|_| async {
        Ok::<_, hyper::Error>(service_fn(serve_req))
    }));

    if let Err(err) = serve_future.await {
        eprintln!("server error: {}", err);
    }
}
```
It's an echo webserver that logs metrics for called paths, it lasted more or less 50 minutes before stopping, I've started with a call every 0.5 seconds but at some point I've bombed it with 3 different parallel calls without pauses, with:
```bash
while [ true ]; do curl -d "kijhfadsohiuagdhoiuagdohisgadhopsigd" http://127.0.0.1:9898/trallalla & curl -d "asf" http://127.0.0.1:9898/trololo & curl -d "srhsdhf" http://127.0.0.1:9898/trelele & echo 1; done
```

![image](https://user-images.githubusercontent.com/7566389/146601082-5f0bd948-768a-4dea-b1ac-40938080968f.png)

**Comment by TommyCpp** [comment] 2021-12-19 01:08
> * Batch seems to be accumulative instead of resetting at each reporting period

So I dig a little bit. I think we can add `.with_export_kind(ExportKindSelector::Delta)` to the OTLP metrics pipeline, this should force the SDK to reset in every batch.

**Comment by TommyCpp** [comment] 2021-12-19 01:40
> * Metrics stops to changes after a while even if it should.

I was able to reproduce the problem fairly quickly with `value_recorder`. Here is my current theory.

I notice you are using a `value_recorder` with `Exact` aggregation(and also cumulative). This will consume a lot of memory and also slow down the exporting because with `Exact` aggregation `value_recorder` will use [array aggregation](https://github.com/open-telemetry/opentelemetry-rust/blob/ccc8fb210c046856825e283940850478521c9c8b/opentelemetry/src/sdk/metrics/selectors/simple.rs#L49). This aggregation will send every data point to the back end. That will put a lot of pressure when exporting because the exporter will clone some of the values. 

In this case, maybe use `ExportKindSelector::Delta` will help. Or you can try to compute histogram within application using [Histogram](https://github.com/open-telemetry/opentelemetry-rust/blob/ccc8fb210c046856825e283940850478521c9c8b/opentelemetry/src/sdk/metrics/selectors/simple.rs#L26).

**Comment by nappa85** [comment] 2021-12-19 13:19
Is it possible to output an error log when  this happens? It would be very
helpful for troubleshooting.

Can I help with patch development? Or just with the tests?

Il dom 19 dic 2021, 02:40 Zhongyang Wu ***@***.***> ha
scritto:

**Comment by TommyCpp** [comment] 2021-12-21 14:28
> Is it possible to output an error log when this happens? It would be very helpful for troubleshooting

Yeah, I think we should probably have some kind of load testing for OTLPmetrics exporter.

Also may help us find the bottleneck. 

As of cumulative vs delta. It's more like a feature and usually, users use cumulative. But yeah we should probably include some kind of warning when users use cumulative and exact aggregation.

**Comment by nappa85** [comment] 2022-01-10 11:55
Sorry for the long silence.
I'm doing some more tests, with Selector::Inexpensive I've some `ValueRecorder<f64>` used to track query times that stopped working, both using `ExportKindSelector::Delta` and `ExportKindSelector::Stateless`.
Now I'm testing with `Selector::Inexpensive` and `ExportKindSelector::Delta`, values started flowing again, I'm waiting some hours to see if this thread's original problem shows up again

**Comment by jtescher** [comment] 2023-07-30 17:00
Closing this for now as metrics have been rewritten. Feel free to re-open if the issue occurs again.

**Closed by jtescher** 2023-07-30 17:00 UTC
Labels: question, area:metrics
