### ISSUE TITLE
[Bug]: Metrics - Gauge stops reporting after being recorded

### ISSUE THREAD

**Issue by cpaika** [open-telemetry/opentelemetry-rust#1975] opened 2024-07-30 23:11 UTC
### What happened?

In our application we periodically record a Gauge<u64> every 60 seconds.  We use the `opentelemetry-prometheus` exporter and host a metrics endpoint where we scrape our prometheus metrics from OpenTelemetry.

We have other metrics (Histogram, Counter) that always show up on our prometheus metrics endpoint.  However for gauges, if more than a second goes by between calls to `record` for the gauge - the gauge stops being exposed on our prometheus endpoint, the metric value, description, and type all dissapear.  It then returns when we record the Gauge. 

We tried switching to the `opentelemetry_stdout` library instead of prometheus and saw the same behavior - the gauge would disappear from the metrics exporter within a second or two after it was last recorded, and then reappear when we recorded a new value.

For context, our prometheus instance scrapes our application periodically every 5s.  So with the Gauge intermittently deregistering itself, we have a race condition where we may not be recording the Gauge value.

Is this known, intended behavior? I wasn't able to find a reference to this in the [opentelemetry spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#gauge) on gauges.  If it is intended - is there any way to customize the Gauge expiration so we can have it persist in the metrics provider context for longer?

### API Version

0.24

### SDK Version

0.24

### What Exporter(s) are you seeing the problem on?

Prometheus

**Comment by cijothomas** [comment] 2024-07-30 23:19
Can you confirm if you are using ObservableGauge or Gauge?

**Comment by cpaika** [comment] 2024-07-30 23:24
> Can you confirm if you are using ObservableGauge or Gauge?

Yes we're using Gauge, not the `ObservableGauge`

**Comment by cijothomas** [comment] 2024-07-30 23:42
I tried the below and it seems working fine for me.. Could you compare what is the difference between the repo app and this? 

For Gauge, as long as new values are reported, it'll be exported.. Maybe that is the wrong behavior?


```
use opentelemetry::global;
use opentelemetry::KeyValue;
use opentelemetry_sdk::metrics::{PeriodicReader, SdkMeterProvider};
use opentelemetry_sdk::{runtime, Resource};
use std::error::Error;
use std::time::Duration;

fn init_meter_provider() -> opentelemetry_sdk::metrics::SdkMeterProvider {
    let exporter = opentelemetry_stdout::MetricsExporterBuilder::default()
        // uncomment the below lines to pretty print output.
        //  .with_encoder(|writer, data|
        //    Ok(serde_json::to_writer_pretty(writer, &data).unwrap()))
        .build();
    let reader = PeriodicReader::builder(exporter, runtime::Tokio).with_interval(Duration::from_secs(5)).build();
    let provider = SdkMeterProvider::builder()
        .with_reader(reader)
        .with_resource(Resource::new([KeyValue::new(
            "service.name",
            "metrics-basic-example",
        )]))
        .build();
    global::set_meter_provider(provider.clone());
    provider
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error + Send + Sync + 'static>> {
    // Initialize the MeterProvider with the stdout Exporter.
    let meter_provider = init_meter_provider();

    // Create a meter from the above MeterProvider.
    let meter = global::meter("mylibraryname");

    // Create a Gauge Instrument.
    let gauge = meter
        .f64_gauge("my_gauge")
        .with_description("A gauge set to 1.0")
        .with_unit("myunit")
        .init();

    gauge.record(
        1.0,
        &[
            KeyValue::new("mykey1", "myvalue1"),
            KeyValue::new("mykey2", "myvalue2"),
        ],
    );

    // Create a ObservableGauge instrument and register a callback that reports the measurement.
    let _observable_gauge = meter
        .f64_observable_gauge("my_observable_gauge")
        .with_description("An observable gauge set to 1.0")
        .with_unit("myunit")
        .with_callback(|observer| {
            observer.observe(
                1.0,
                &[
                    KeyValue::new("mykey1", "myvalue1"),
                    KeyValue::new("mykey2", "myvalue2"),
                ],
            )
        })
        .init();

    // Metrics are exported by default every 30 seconds when using stdout exporter,
    // however shutting down the MeterProvider here instantly flushes
    // the metrics, instead of waiting for the 30 sec interval.
    while (true) {
        gauge.record(
            1.0,
            &[
                KeyValue::new("mykey1", "myvalue1"),
                KeyValue::new("mykey2", "myvalue2"),
            ],
        );
        std::thread::sleep(std::time::Duration::from_secs(1));
    }
    meter_provider.shutdown()?;
    Ok(())
}

```

**Comment by cpaika** [comment] 2024-07-31 00:02
Thanks for the code - tweaked the timing to get a reproduction:
```rust
use opentelemetry::global;
use opentelemetry::KeyValue;
use opentelemetry_sdk::metrics::{PeriodicReader, SdkMeterProvider};
use opentelemetry_sdk::{runtime, Resource};
use std::error::Error;
use std::time::Duration;

fn init_meter_provider() -> opentelemetry_sdk::metrics::SdkMeterProvider {
    let exporter = opentelemetry_stdout::MetricsExporterBuilder::default()
        .build();
    let reader = PeriodicReader::builder(exporter, runtime::Tokio).with_interval(Duration::from_secs(1)).build();
    let provider = SdkMeterProvider::builder()
        .with_reader(reader)
        .with_resource(Resource::new([KeyValue::new(
            "service.name",
            "metrics-basic-example",
        )]))
        .build();
    global::set_meter_provider(provider.clone());
    provider
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error + Send + Sync + 'static>> {
    // Initialize the MeterProvider with the stdout Exporter.
    let meter_provider = init_meter_provider();

    // Create a meter from the above MeterProvider.
    let meter = global::meter("mylibraryname");

    // Create a Gauge Instrument.
    let gauge = meter
        .f64_gauge("my_gauge")
        .with_description("A gauge set to 1.0")
        .with_unit("myunit")
        .init();

    gauge.record(
        1.0,
        &[
            KeyValue::new("mykey1", "myvalue1"),
            KeyValue::new("mykey2", "myvalue2"),
        ],
    );

    // Create a ObservableGauge instrument and register a callback that reports the measurement.
    let _observable_gauge = meter
        .f64_observable_gauge("my_observable_gauge")
        .with_description("An observable gauge set to 1.0")
        .with_unit("myunit")
        .with_callback(|observer| {
            observer.observe(
                1.0,
                &[
                    KeyValue::new("mykey1", "myvalue1"),
                    KeyValue::new("mykey2", "myvalue2"),
                ],
            )
        })
        .init();

    while (true) {
        gauge.record(
            1.0,
            &[
                KeyValue::new("mykey1", "myvalue1"),
                KeyValue::new("mykey2", "myvalue2"),
            ],
        );
        std::thread::sleep(std::time::Duration::from_secs(5));
    }
    meter_provider.shutdown()?;
    Ok(())
}
```


What happens is every 5 seconds the Gauge records a value.  The exporter ticks every 1 second.  After 1 second, the previous Gauge value is gone (only the `ObservableGauge` is present since that uses the `observe` pattern). 

What's the criteria for expiring the Gauge reading?  It's unintuitive to me that it would disappear from the metrics, I would of expected it to stay with the previous value.  With the `opentelemetry-prometheus` exporter we're seeing missed gauge measurements, where even though our Gauge is recording a value and our Prometheus server is scraping the application, there's the race and the Gauge sometimes isn't present in the response - I think that's related to this behavior.

Example log output where you can see the `my_gauge` dissapear:
```
{"resourceMetrics":{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"metrics-basic-example"}}]},"scopeMetrics":[{"scope":{"name":"mylibraryname"},"metrics":[{"name":"my_gauge","description":"A gauge set to 1.0","unit":"myunit","gauge":{"dataPoints":[{"attributes":[{"key":"mykey1","value":{"stringValue":"myvalue1"}},{"key":"mykey2","value":{"stringValue":"myvalue2"}}],"startTime":null,"time":"2024-07-30 23:57:19.777","startTimeUnixNano":null,"timeUnixNano":1722383839777711000,"value":1.0}]}},{"name":"my_observable_gauge","description":"An observable gauge set to 1.0","unit":"myunit","gauge":{"dataPoints":[{"attributes":[{"key":"mykey1","value":{"stringValue":"myvalue1"}},{"key":"mykey2","value":{"stringValue":"myvalue2"}}],"startTime":null,"time":"2024-07-30 23:57:19.777","startTimeUnixNano":null,"timeUnixNano":1722383839777766000,"value":1.0}]}}]}]}}
{"resourceMetrics":{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"metrics-basic-example"}}]},"scopeMetrics":[{"scope":{"name":"mylibraryname"},"metrics":[{"name":"my_observable_gauge","description":"An observable gauge set to 1.0","unit":"myunit","gauge":{"dataPoints":[{"attributes":[{"key":"mykey1","value":{"stringValue":"myvalue1"}},{"key":"mykey2","value":{"stringValue":"myvalue2"}}],"startTime":null,"time":"2024-07-30 23:57:20.782","startTimeUnixNano":null,"timeUnixNano":1722383840782181000,"value":1.0}]}}]}]}}
{"resourceMetrics":{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"metrics-basic-example"}}]},"scopeMetrics":[{"scope":{"name":"mylibraryname"},"metrics":[{"name":"my_observable_gauge","description":"An observable gauge set to 1.0","unit":"myunit","gauge":{"dataPoints":[{"attributes":[{"key":"mykey1","value":{"stringValue":"myvalue1"}},{"key":"mykey2","value":{"stringValue":"myvalue2"}}],"startTime":null,"time":"2024-07-30 23:57:21.778","startTimeUnixNano":null,"timeUnixNano":1722383841778354000,"value":1.0}]}}]}]}}
{"resourceMetrics":{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"metrics-basic-example"}}]},"scopeMetrics":[{"scope":{"name":"mylibraryname"},"metrics":[{"name":"my_observable_gauge","description":"An observable gauge set to 1.0","unit":"myunit","gauge":{"dataPoints":[{"attributes":[{"key":"mykey1","value":{"stringValue":"myvalue1"}},{"key":"mykey2","value":{"stringValue":"myvalue2"}}],"startTime":null,"time":"2024-07-30 23:57:22.780","startTimeUnixNano":null,"timeUnixNano":1722383842780002000,"value":1.0}]}}]}]}}
{"resourceMetrics":{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"metrics-basic-example"}}]},"scopeMetrics":[{"scope":{"name":"mylibraryname"},"metrics":[{"name":"my_observable_gauge","description":"An observable gauge set to 1.0","unit":"myunit","gauge":{"dataPoints":[{"attributes":[{"key":"mykey1","value":{"stringValue":"myvalue1"}},{"key":"mykey2","value":{"stringValue":"myvalue2"}}],"startTime":null,"time":"2024-07-30 23:57:23.780","startTimeUnixNano":null,"timeUnixNano":1722383843780527000,"value":1.0}]}}]}]}}
{"resourceMetrics":{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"metrics-basic-example"}}]},"scopeMetrics":[{"scope":{"name":"mylibraryname"},"metrics":[{"name":"my_observable_gauge","description":"An observable gauge set to 1.0","unit":"myunit","gauge":{"dataPoints":[{"attributes":[{"key":"mykey1","value":{"stringValue":"myvalue1"}},{"key":"mykey2","value":{"stringValue":"myvalue2"}}],"startTime":null,"time":"2024-07-30 23:57:24.780","startTimeUnixNano":null,"timeUnixNano":1722383844780104000,"value":1.0}]}}]}]}}
{"resourceMetrics":{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"metrics-basic-example"}}]},"scopeMetrics":[{"scope":{"name":"mylibraryname"},"metrics":[{"name":"my_gauge","description":"A gauge set to 1.0","unit":"myunit","gauge":{"dataPoints":[{"attributes":[{"key":"mykey1","value":{"stringValue":"myvalue1"}},{"key":"mykey2","value":{"stringValue":"myvalue2"}}],"startTime":null,"time":"2024-07-30 23:57:24.782","startTimeUnixNano":null,"timeUnixNano":1722383844782352000,"value":1.0}]}},{"name":"my_observable_gauge","description":"An observable gauge set to 1.0","unit":"myunit","gauge":{"dataPoints":[{"attributes":[{"key":"mykey1","value":{"stringValue":"myvalue1"}},{"key":"mykey2","value":{"stringValue":"myvalue2"}}],"startTime":null,"time":"2024-07-30 23:57:25.781","startTimeUnixNano":null,"timeUnixNano":1722383845781481000,"value":1.0}]}}]}]}}
{"resourceMetrics":{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"metrics-basic-example"}}]},"scopeMetrics":[{"scope":{"name":"mylibraryname"},"metrics":[{"name":"my_observable_gauge","description":"An observable gauge set to 1.0","unit":"myunit","gauge":{"dataPoints":[{"attributes":[{"key":"mykey1","value":{"stringValue":"myvalue1"}},{"key":"mykey2","value":{"stringValue":"myvalue2"}}],"startTime":null,"time":"2024-07-30 23:57:26.781","startTimeUnixNano":null,"timeUnixNano":1722383846781511000,"value":1.0}]}}]}]}}
```

**Comment by cijothomas** [comment] 2024-07-31 00:56
> What happens is every 5 seconds the Gauge records a value. The exporter ticks every 1 second. After 1 second, the previous Gauge value is gone (only the ObservableGauge is present since that uses the observe pattern).

Good point. For instruments which has the notion of Temporality, the previous value is expected to be continued to be reported, even when no new measurements are provided. That explains why Counter/Histogram/UpDownCounter works the way you are expecting.

Gauge has no notion of temporality, so that begs the question - do we ever "forget" Gauge if no new measurement comes? It looks like current implementation is forgetting Gauge if no new measurement comes, but I'll need to check with OTel spec to see if that is the expected behavior or not.

(I have worked in OTel Metrics in .NET quite a bit, except Gauge, as .NET still don't have Gauge instrument! I'll get back after checking more, as my Gauge knowledge seems to be lacking!)

**Comment by cijothomas** [comment] 2024-07-31 01:08
https://github.com/open-telemetry/opentelemetry-specification/pull/3540/files#diff-32d5f289beed96900fa1e6e69a3ee9cc0b6503ce8883672011c44bc772c0fa2aR1099

It looks like the temporality should be respected for Gauge, even if the Gauge datapoint has no concept of temporality. So this is a bug in OTel Rust implementation. Thanks @cpaika for raising this. I'll self-assign to work on this. (In the middle of major metrics refactor, hopefully I can make this in by next release.)

**Comment by cpaika** [comment] 2024-07-31 14:24
Sounds great - thanks for digging in to this, I appreciate it

**Closed** 2024-08-13 23:40 UTC
Labels: bug, A-metrics

**Comment by hveiga** [comment] 2024-08-19 15:06
Hi folks, thanks for the quick fix. When can we expect a release with it? We are trying to figure out timelines on our side, thanks!

**Comment by cijothomas** [comment] 2024-08-19 16:11
This will be part of the coming release, expected in less than 2 weeks.
