### ISSUE TITLE
SIGINT ignored when using `.install_batch(opentelemetry::runtime::Tokio)`

### ISSUE THREAD

**Issue by rex-remind101** [open-telemetry/opentelemetry-rust#731] opened 2022-02-11 00:48 UTC
I've confirmed that when using `.install_batch(opentelemetry::runtime::Tokio)` I cannot stop the running program via `^C` (in my case with Tokio but maybe this is true for any runtime). When using `.install_simple()` I can use SIGINT to kill the program no problem.

more here https://github.com/actix/actix-web/issues/2638

**Comment by TommyCpp** [comment] 2022-02-11 05:33
I think you need to use `opentelemetry::runtime::TokioCurrentThread` to start to spawn the background job of opentelemetry in the right place. Alternatively, you can use `#[tokio::main]` instead of `#[actix_web::main]` to start a multi-thread tokio runtime. Then you should be able to use `opentelemetry::runtime::TokioCurrentThread`

**Comment by rex-remind101** [comment] 2022-02-11 22:32
I don't know what those macros do, but I'd imagine `#[actix_web::main]` does more than `#[tokio::main]`, so that wouldn't be a drop in replacement. Is there an example of using both of these together or using `opentelemetry::runtime::TokioCurrentThread` I can follow? Thank you

**Comment by TommyCpp** [comment] 2022-02-13 20:08
There are few options here. One is using [actic-web-opentelemetry](https://github.com/OutThereLabs/actix-web-opentelemetry) repo. Or you can simplely enable `rt-tokio-current-hread` feature in opentelemetry and use `opentelemetry::runtime::TokioCurrentThread`. No other changes needed.

**Comment by rex-remind101** [comment] 2022-02-14 19:57
This worked, thanks. I looked at documentation and the only explanation sort of hinting at the full context of what you said is here https://github.com/open-telemetry/opentelemetry-rust/blob/482772f2317e242e6b98bfe04ed42e4dac8cf77b/opentelemetry/src/sdk/trace/span_processor.rs#L190

**Comment by TommyCpp** [comment] 2022-02-15 16:18
Good point. I updated one of our examples to be more accurate https://github.com/open-telemetry/opentelemetry-rust/pull/734. Also, we should add some additional context on how to choose runtime on the main docs. I will close this for now as the problem is resolved but I will open an action item on [GA issue](https://github.com/open-telemetry/opentelemetry-rust/issues/330) to track the doc updates.

**Closed by TommyCpp** 2022-02-15 16:18 UTC
Labels: question, area:trace
